services:
  # accountsdb:
  #   container_name: accountsdb
  #   ports:
  #     - 3305:3306
  #   environment:
  #     MYSQL_DATABASE: accountsdb
  #   extends:
  #     file: common-config.yml
  #     service: microservice-db-config

  # loansdb:
  #   container_name: loansdb
  #   ports:
  #     - 3307:3306
  #   environment:
  #     MYSQL_DATABASE: loansdb
  #   extends:
  #     file: common-config.yml
  #     service: microservice-db-config

  # cardsdb:
  #   container_name: cardsdb
  #   ports:
  #     - 3308:3306
  #   environment:
  #     MYSQL_DATABASE: cardsdb
  #   extends:
  #     file: common-config.yml
  #     service: microservice-db-config
  # rabbit:
  #   image: rabbitmq:3.13-management
  #   hostname : rabbitmq
  #   ports :
  #     - "5672:5672"
  #     - "15672:15672"
  #   healthcheck:
  #     test: rabbitmq-diagnostics check_port_connectivity
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 10s
  #   extends :
  #     file : common-config.yml
  #     service : network-deploy-service


  configserver:
    image:
      "pokhrailsuresh/configserver:s4"
    container_name:
      configserver-ms
    ports:
     -  "8071:8071"
    # depends_on: 
    #     rabbit :
    #       condition : service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends :
      file : common-config.yml
      service :  microservice-base-config

  eurekaserver:
    image:
      "pokhrailsuresh/eurekaserver:s4"
    container_name:
      eurekaserver-ms
    ports:
     -  "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    # depends_on: 
    #     rabbit :
    #       condition : service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends :
      file : common-config.yml
      service :  microservice-configservice-config
    depends_on:
      configserver :
        condition : service_healthy


  accounts:
    image:
      "pokhrailsuresh/accounts:s4"
    container_name:
      accounts-ms
    ports:
      - "8080:8080"
    environment:
    #   SPRING_APPLICATION_NAME: "accounts"
    #   SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    # depends_on:
    #   accountsdb:
    #     condition: service_healthy
    extends :
      file : common-config.yml
      service : microservice-eurekaservice-config



  loan:
    image:
      "pokhrailsuresh/loan:s4"
    container_name:
      loan-ms
    ports:
     -  "8090:8090"
    # environment:
    #   SPRING_APPLICATION_NAME : "loan"
    #   SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    # depends_on:
    #   loansdb:
    #     condition: service_healthy
    extends :
      file : common-config.yml
      service :  microservice-eurekaservice-config


  cards:
    image:
      "pokhrailsuresh/cards:s4"
    container_name:
      cards-ms
    ports:
     -  "9000:9000" 
    # environment:
    #   SPRING_APPLICATION_NAME : "cards"
    #   SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    # depends_on:
    #   cardsdb:
    #     condition: service_healthy
    extends :
      file : common-config.yml
      service :  microservice-eurekaservice-config
  
    
networks:
  bank:
    driver: "bridge"
  
  
