server:
  port: 8090
spring:
  application:
    name: "loan"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb #3307
    username: root
    password: 'root'
  jpa:
     #database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
     # ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always 
  config:
    import: "optional:configserver:http://localhost:8071/"
  # rabbitmq :
  #   host : "localhost"
  #   port : 5672
  #   username : "guest"
  #   password : "guest"

management : 
  endpoints :
    web :
      exposure :
        include : "*"
  health : 
    readiness-state:
      enabled : true
    liveness-state :
      enable : true
  endpoint:
    shutdown:
      enabled: true
    health :
      probes : 
        enabled : true
  info:
    env:
      enabled: true

endpoints:
    shutdown:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info: 
  app:  
    name: "loan"
    description: "Bank Loans Application"
    version: "1.0.0"
logging:
  level:
    com:
      bank:
        loan: DEBUG


 