spring:
    application:
        name : "configserver"
    profiles :
        #active : native
        active : git
    cloud :
        config :
            server :
                git : 
                    uri : "https://github.com/suresh-pokhrail/config.git"
                    default-label : main
                    timeout : 5 #sec
                    clone-on-start : true
                    force-pull : true 
                #native :
                   # search-locations : "classpath:/config"
                   # search-locations : "file:///F://NPS//project//config"
    # rabbitmq :
    #     host : "localhost"
    #     port : 5672
    #     username : "guest"
    #     password : "guest"

management : 
    endpoints :
        web :
            exposure :
                include: "*"
    health : 
        readiness-state:
            enabled : true
        liveness-state :
            enable : true
    endpoint:
        health :
            probes : 
                enabled : true

encrypt :
    key : "sureshpokhrail1234567890"
server:
    port: 8071
